#!/bin/bash

# override properties like:
# export environment_music_scrobbling1_baseurl="http://localhost:"
export service_aws_ec2_url="http://localhost:${RESTDRIVER_PORT:="8081"}"
export service_aws_elb_url="http://localhost:${RESTDRIVER_PORT:="8081"}"
export service_aws_iam_url="http://localhost:${RESTDRIVER_PORT:="8081"}"
export service_aws_s3_url="http://localhost:${RESTDRIVER_PORT:="8081"}"
export service_aws_ddb_url="http://localhost:${RESTDRIVER_PORT:="8081"}"

. test_helper.sh
TIMEOUT=60

if [ "$1" != "wait" ]
then
    run_test "shuppet.acceptance" $TIMEOUT
else
    lein ring server-headless
fi
