#!/bin/bash

# override properties like:
# export environment_music_scrobbling1_baseurl="http://localhost:"

. test_helper.sh
TIMEOUT=60

if [ "$1" != "wait" ]
then
    run_test "shuppet.integration" $TIMEOUT
else
    lein ring server-headless
fi
